name: todo_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  easy_date_timeline: ^1.0.3
  firebase_core: ^2.25.4
  firebase: ^9.0.3
  auth: ^8.2.0+02
  firebase_auth: ^4.17.4
  flutter_easyloading: ^3.0.5
  animated_custom_dropdown: ^3.0.0
  bot_toast: ^4.1.3
  lottie: ^3.0.0
  cloud_firestore: ^4.15.6
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true


  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf